site_name: Dug Developer Documentation
site_url: https://dug.readthedocs.org
repo_url: https://github.com/helxplatform/search-documentation

nav:
    - Overview:
        - Introduction: index.md
        - Dug Architecture: architecture/dug.md
        - Roger Architecture: architecture/roger.md
        - Frequently Asked Questions: faq.md
        - License: license.md
    - Development Guide:
        - Dug:
          - Quick Start: development-guide/dug/index.md
          - Configuration: development-guide/dug/config.md
          - Parsers: development-guide/dug/parsers.md
          - Annotators: development-guide/dug/annotators.md
          - Concept Expansion: development-guide/dug/concept-expansion.md
          - Dug search web API: development-guide/dug/web-api.md
        - Roger:
          - Quick Start: development-guide/roger/index.md
          - Pipeline structure: development-guide/roger/pipelines.md
          - Configuration: development-guide/roger/config.md
        - Tutorials:
          - Adding a Parser: tutorials/parsers.md
          - Adding an Annotator: tutorials/annotators.md
    - Deployment Guide:
        - Introduction: deployment-guide/index.md
        - CI/CD:
            - Continuous Integration for Dug: deployment-guide/dug.md
            - Continuous Integration for Roger: deployment-guide/roger.md
        - Helm Chart: deployment-guide/helm.md


#extra_css:
#  - stylesheets/extra.css

theme:
    name: "material"
#    favicon: img/favicon.ico
#    logo: img/favicon.ico
    icon:
        admonition:
        server: material/server
    language: en
    # Pick color: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: custom
          toggle:
              icon: material/weather-night
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: custom
          toggle:
              icon: material/weather-sunny
              name: Switch to light mode
    features:
        - navigation.indexes
        - navigation.footer
        - navigation.sections
        - navigation.top
        - navigation.tracking
        - content.code.copy
        - content.code.annotate
        - content.code.select
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow

copyright: Copyright &copy; 2017-2023 Dug<br>RENCI & RTI

markdown_extensions:
    - admonition # Supported types: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.details
    - pymdownx.extra
    - abbr
    - pymdownx.snippets:
        auto_append:
            - docs/includes/abbreviations.md
    - attr_list
    - smarty

plugins:
    - search
    - mermaid2
    - autorefs
    - glightbox:
        touchNavigation: true
        loop: false
        effect: zoom
        slide_effect: slide
        width: 100%
        height: auto
        zoomable: true
        draggable: true
        auto_caption: false
        caption_position: bottom

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/helxplatform/dug

watch:
    - docs